version: 1
builder:
  configs:
    - documentation_targets: [Plexy, PlexyActions, PlexyCard, PlexyComponents, PlexySession, PlexyDropIn, PlexyEncryption, PlexyWeChatPay, PlexyCashAppPay, PlexyTwint]
      platform: ios
