sonar.host.url=https://sonarcloud.io
sonar.organization=plexy
sonar.projectKey=Plexy_plexy-ios
sonar.sourceEncoding=UTF-8
sonar.language=swift

sonar.swift.project=Plexy.xcodeproj
sonar.sources=Plexy,PlexyActions,PlexyCard,PlexyCashAppPay,PlexyComponents,PlexyEncryption,PlexyDropIn,PlexySession,PlexySwiftUI,PlexyWeChatPay

sonar.exclusion=Tests,Docs,Internal,SnapshotTests,PlexyUnitTests

#sonar.coverageReportPaths=reports/sonarqube-generic-coverage.xml
#sonar.swift.coverage.reportPaths=reports/sonarqube-generic-coverage.xml
sonar.swift.swiftLint.reportPaths=reports/swiftlint.json
sonar.cfamily.build-wrapper-output=reports/build-wrapper

# Ignoring C, C++
sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-
